# Generated by Django 2.2.7 on 2019-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('highest_elevation', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coastline', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
